package com.school.model;

// Generated Jun 16, 2015 4:57:47 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusDelayDetails generated by hbm2java
 */
@Entity
@Table(name = "bus_delay_details", catalog = "school_db")
public class BusDelayDetails implements java.io.Serializable {

	private Integer id;
	private BusInfo busInfo;
	private Date delayTime;
	private Date delayedOn;
	private Byte type;
	private Byte notificationSent;
	private String description;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;
	private Byte delayInMins;

	public BusDelayDetails() {
	}

	public BusDelayDetails(BusInfo busInfo, Date delayTime, Date delayedOn,
			Byte type, Byte notificationSent, String description,
			Date lastUpdatedOn, Integer lastUpdatedBy, Byte delayInMins) {
		this.busInfo = busInfo;
		this.delayTime = delayTime;
		this.delayedOn = delayedOn;
		this.type = type;
		this.notificationSent = notificationSent;
		this.description = description;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
		this.delayInMins = delayInMins;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bus_id")
	public BusInfo getBusInfo() {
		return this.busInfo;
	}

	public void setBusInfo(BusInfo busInfo) {
		this.busInfo = busInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delay_time", length = 19)
	public Date getDelayTime() {
		return this.delayTime;
	}

	public void setDelayTime(Date delayTime) {
		this.delayTime = delayTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "delayed_on", length = 10)
	public Date getDelayedOn() {
		return this.delayedOn;
	}

	public void setDelayedOn(Date delayedOn) {
		this.delayedOn = delayedOn;
	}

	@Column(name = "type")
	public Byte getType() {
		return this.type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	@Column(name = "notification_sent")
	public Byte getNotificationSent() {
		return this.notificationSent;
	}

	public void setNotificationSent(Byte notificationSent) {
		this.notificationSent = notificationSent;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Column(name = "delay_in_mins")
	public Byte getDelayInMins() {
		return this.delayInMins;
	}

	public void setDelayInMins(Byte delayInMins) {
		this.delayInMins = delayInMins;
	}

}
