package com.school.model;

// Generated Jun 26, 2015 2:39:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusInfo generated by hbm2java
 */
@Entity
@Table(name = "bus_info")
public class BusInfo implements java.io.Serializable {

	private Integer id;
	private String title;
	private String busNumber;
	private String vehicleNo;
	private String busDriverName;
	private String contactNo;
	private String description;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;
	private Set<SchoolBus> schoolBuses = new HashSet<SchoolBus>(0);
	private Set<BusDriver> busDrivers = new HashSet<BusDriver>(0);
	private Set<BusRoute> busRoutes = new HashSet<BusRoute>(0);
	private Set<BusDelayDetails> busDelayDetailses = new HashSet<BusDelayDetails>(
			0);

	public BusInfo() {
	}

	public BusInfo(String title, String busNumber, String vehicleNo,
			String busDriverName, String contactNo, String description,
			Date lastUpdatedOn, Integer lastUpdatedBy,
			Set<SchoolBus> schoolBuses, Set<BusDriver> busDrivers,
			Set<BusRoute> busRoutes, Set<BusDelayDetails> busDelayDetailses) {
		this.title = title;
		this.busNumber = busNumber;
		this.vehicleNo = vehicleNo;
		this.busDriverName = busDriverName;
		this.contactNo = contactNo;
		this.description = description;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
		this.schoolBuses = schoolBuses;
		this.busDrivers = busDrivers;
		this.busRoutes = busRoutes;
		this.busDelayDetailses = busDelayDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "bus_number", length = 10)
	public String getBusNumber() {
		return this.busNumber;
	}

	public void setBusNumber(String busNumber) {
		this.busNumber = busNumber;
	}

	@Column(name = "vehicle_no", length = 20)
	public String getVehicleNo() {
		return this.vehicleNo;
	}

	public void setVehicleNo(String vehicleNo) {
		this.vehicleNo = vehicleNo;
	}

	@Column(name = "bus_driver_name", length = 100)
	public String getBusDriverName() {
		return this.busDriverName;
	}

	public void setBusDriverName(String busDriverName) {
		this.busDriverName = busDriverName;
	}

	@Column(name = "contact_no", length = 20)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "busInfo")
	public Set<SchoolBus> getSchoolBuses() {
		return this.schoolBuses;
	}

	public void setSchoolBuses(Set<SchoolBus> schoolBuses) {
		this.schoolBuses = schoolBuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "busInfo")
	public Set<BusDriver> getBusDrivers() {
		return this.busDrivers;
	}

	public void setBusDrivers(Set<BusDriver> busDrivers) {
		this.busDrivers = busDrivers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "busInfo")
	public Set<BusRoute> getBusRoutes() {
		return this.busRoutes;
	}

	public void setBusRoutes(Set<BusRoute> busRoutes) {
		this.busRoutes = busRoutes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "busInfo")
	public Set<BusDelayDetails> getBusDelayDetailses() {
		return this.busDelayDetailses;
	}

	public void setBusDelayDetailses(Set<BusDelayDetails> busDelayDetailses) {
		this.busDelayDetailses = busDelayDetailses;
	}

}
