package com.school.model;

// Generated Jun 9, 2015 5:02:23 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusRouteStop generated by hbm2java
 */
@Entity
@Table(name = "bus_route_stop", catalog = "school_db")
public class BusRouteStop implements java.io.Serializable {

	private Integer id;
	private Route route;
	private BusStop busStop;
	private Integer busStopNo;
	private Date busPickTime;
	private Date busDropTime;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;

	public BusRouteStop() {
	}

	public BusRouteStop(Route route, BusStop busStop, Integer busStopNo,
			Date busPickTime, Date busDropTime, Date lastUpdatedOn,
			Integer lastUpdatedBy) {
		this.route = route;
		this.busStop = busStop;
		this.busStopNo = busStopNo;
		this.busPickTime = busPickTime;
		this.busDropTime = busDropTime;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "route_id")
	public Route getRoute() {
		return this.route;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stop_id")
	public BusStop getBusStop() {
		return this.busStop;
	}

	public void setBusStop(BusStop busStop) {
		this.busStop = busStop;
	}

	@Column(name = "bus_stop_no")
	public Integer getBusStopNo() {
		return this.busStopNo;
	}

	public void setBusStopNo(Integer busStopNo) {
		this.busStopNo = busStopNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bus_pick_time", length = 19)
	public Date getBusPickTime() {
		return this.busPickTime;
	}

	public void setBusPickTime(Date busPickTime) {
		this.busPickTime = busPickTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bus_drop_time", length = 19)
	public Date getBusDropTime() {
		return this.busDropTime;
	}

	public void setBusDropTime(Date busDropTime) {
		this.busDropTime = busDropTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
