package com.school.model;

// Generated Jun 9, 2015 5:02:23 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusStop generated by hbm2java
 */
@Entity
@Table(name = "bus_stop", catalog = "school_db")
public class BusStop implements java.io.Serializable {

	private Integer id;
	private String name;
	private String pickupLatitude;
	private String pickupLongitude;
	private String dropLatitude;
	private String dropLongitude;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;
	private Boolean status;
	private Set userBuses = new HashSet(0);
	private Set busRouteStops = new HashSet(0);

	public BusStop() {
	}

	public BusStop(String name, String pickupLatitude, String pickupLongitude,
			String dropLatitude, String dropLongitude, Date lastUpdatedOn,
			Integer lastUpdatedBy, Boolean status, Set userBuses,
			Set busRouteStops) {
		this.name = name;
		this.pickupLatitude = pickupLatitude;
		this.pickupLongitude = pickupLongitude;
		this.dropLatitude = dropLatitude;
		this.dropLongitude = dropLongitude;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
		this.status = status;
		this.userBuses = userBuses;
		this.busRouteStops = busRouteStops;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "pickup_latitude", length = 15)
	public String getPickupLatitude() {
		return this.pickupLatitude;
	}

	public void setPickupLatitude(String pickupLatitude) {
		this.pickupLatitude = pickupLatitude;
	}

	@Column(name = "pickup_longitude", length = 15)
	public String getPickupLongitude() {
		return this.pickupLongitude;
	}

	public void setPickupLongitude(String pickupLongitude) {
		this.pickupLongitude = pickupLongitude;
	}

	@Column(name = "drop_latitude", length = 15)
	public String getDropLatitude() {
		return this.dropLatitude;
	}

	public void setDropLatitude(String dropLatitude) {
		this.dropLatitude = dropLatitude;
	}

	@Column(name = "drop_longitude", length = 15)
	public String getDropLongitude() {
		return this.dropLongitude;
	}

	public void setDropLongitude(String dropLongitude) {
		this.dropLongitude = dropLongitude;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "busStop")
	public Set getUserBuses() {
		return this.userBuses;
	}

	public void setUserBuses(Set userBuses) {
		this.userBuses = userBuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "busStop")
	public Set getBusRouteStops() {
		return this.busRouteStops;
	}

	public void setBusRouteStops(Set busRouteStops) {
		this.busRouteStops = busRouteStops;
	}

}
