package com.school.model;

// Generated Jun 26, 2015 2:39:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CategoryOptionFeature generated by hbm2java
 */
@Entity
@Table(name = "category_option_feature", catalog = "school_db")
public class CategoryOptionFeature implements java.io.Serializable {

	private Integer id;
	private CategoryOption categoryOption;
	private String label;
	private String dataType;
	private Float weightage;

	public CategoryOptionFeature() {
	}

	public CategoryOptionFeature(CategoryOption categoryOption) {
		this.categoryOption = categoryOption;
	}

	public CategoryOptionFeature(CategoryOption categoryOption, String label,
			String dataType, Float weightage) {
		this.categoryOption = categoryOption;
		this.label = label;
		this.dataType = dataType;
		this.weightage = weightage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_option_id", nullable = false)
	public CategoryOption getCategoryOption() {
		return this.categoryOption;
	}

	public void setCategoryOption(CategoryOption categoryOption) {
		this.categoryOption = categoryOption;
	}

	@Column(name = "label", length = 200)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "data_type", length = 200)
	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	@Column(name = "weightage", precision = 9, scale = 3)
	public Float getWeightage() {
		return this.weightage;
	}

	public void setWeightage(Float weightage) {
		this.weightage = weightage;
	}

}
