package com.school.model;

// Generated Jun 16, 2015 4:57:47 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "school_db")
public class City implements java.io.Serializable {

	private Integer id;
	private Tehsil tehsil;
	private String name;
	private Integer isCity;
	private Integer sortOrder;
	private Byte status;
	private Set<Locality> localities = new HashSet<Locality>(0);
	private Set<SchoolBankAccountDetails> schoolBankAccountDetailses = new HashSet<SchoolBankAccountDetails>(
			0);

	public City() {
	}

	public City(Tehsil tehsil, String name, Integer isCity, Integer sortOrder,
			Byte status, Set<Locality> localities,
			Set<SchoolBankAccountDetails> schoolBankAccountDetailses) {
		this.tehsil = tehsil;
		this.name = name;
		this.isCity = isCity;
		this.sortOrder = sortOrder;
		this.status = status;
		this.localities = localities;
		this.schoolBankAccountDetailses = schoolBankAccountDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tehsil_id")
	@JsonBackReference
	public Tehsil getTehsil() {
		return this.tehsil;
	}

	public void setTehsil(Tehsil tehsil) {
		this.tehsil = tehsil;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_city")
	public Integer getIsCity() {
		return this.isCity;
	}

	public void setIsCity(Integer isCity) {
		this.isCity = isCity;
	}

	@Column(name = "sort_order")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
    @JsonManagedReference
	public Set<Locality> getLocalities() {
		return this.localities;
	}

	public void setLocalities(Set<Locality> localities) {
		this.localities = localities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
    @JsonManagedReference
	public Set<SchoolBankAccountDetails> getSchoolBankAccountDetailses() {
		return this.schoolBankAccountDetailses;
	}

	public void setSchoolBankAccountDetailses(
			Set<SchoolBankAccountDetails> schoolBankAccountDetailses) {
		this.schoolBankAccountDetailses = schoolBankAccountDetailses;
	}

}
