package com.school.model;

// Generated Jun 9, 2015 5:02:23 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClassAccessories generated by hbm2java
 */
@Entity
@Table(name = "class_accessories", catalog = "school_db")
public class ClassAccessories implements java.io.Serializable {

	private Integer id;
	private Accessories accessories;
	private ClassInfo classInfo;
	private ContactInfoExternal contactInfoExternal;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;

	public ClassAccessories() {
	}

	public ClassAccessories(Accessories accessories, ClassInfo classInfo,
			ContactInfoExternal contactInfoExternal, Date lastUpdatedOn,
			Integer lastUpdatedBy) {
		this.accessories = accessories;
		this.classInfo = classInfo;
		this.contactInfoExternal = contactInfoExternal;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accessories_id")
	public Accessories getAccessories() {
		return this.accessories;
	}

	public void setAccessories(Accessories accessories) {
		this.accessories = accessories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id")
	public ClassInfo getClassInfo() {
		return this.classInfo;
	}

	public void setClassInfo(ClassInfo classInfo) {
		this.classInfo = classInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "section_id")
	public ContactInfoExternal getContactInfoExternal() {
		return this.contactInfoExternal;
	}

	public void setContactInfoExternal(ContactInfoExternal contactInfoExternal) {
		this.contactInfoExternal = contactInfoExternal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
