package com.school.model;

// Generated Jun 16, 2015 4:57:47 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonManagedReference;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Locality generated by hbm2java
 */
@Entity
@Table(name = "locality", catalog = "school_db")
public class Locality implements java.io.Serializable {

	private Integer id;
	private City city;
	private String name;
	private Boolean status;
	private Byte sortOrder;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;
	private Set<TeacherExperience> teacherExperiences = new HashSet<TeacherExperience>(
			0);
	private Set<School> schools = new HashSet<School>(0);

	public Locality() {
	}

	public Locality(City city, String name, Boolean status, Byte sortOrder,
			Date lastUpdatedOn, Integer lastUpdatedBy,
			Set<TeacherExperience> teacherExperiences, Set<School> schools) {
		this.city = city;
		this.name = name;
		this.status = status;
		this.sortOrder = sortOrder;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
		this.teacherExperiences = teacherExperiences;
		this.schools = schools;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "city_id")
	@JsonBackReference
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "sort_order")
	public Byte getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Byte sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated_on", length = 10)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locality")
    @JsonManagedReference
	public Set<TeacherExperience> getTeacherExperiences() {
		return this.teacherExperiences;
	}

	public void setTeacherExperiences(Set<TeacherExperience> teacherExperiences) {
		this.teacherExperiences = teacherExperiences;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locality")
    @JsonManagedReference
	public Set<School> getSchools() {
		return this.schools;
	}

	public void setSchools(Set<School> schools) {
		this.schools = schools;
	}

}
