package com.school.model;

// Generated Jun 26, 2015 2:39:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification")
public class Notification implements java.io.Serializable {

	private Integer id;
	private UserRegistrationInfo userRegistrationInfoByFromUserId;
	private UserRegistrationInfo userRegistrationInfoByToUserId;
	private NotificationType notificationType;
	private String subject;
	private String description;
	private Date createdOn;
	private Integer createdBy;
	private Date validFromDate;
	private Date validToDate;
	private Byte status;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;

	public Notification() {
	}

	public Notification(UserRegistrationInfo userRegistrationInfoByFromUserId,
			UserRegistrationInfo userRegistrationInfoByToUserId,
			NotificationType notificationType, String subject,
			String description, Date createdOn, Integer createdBy,
			Date validFromDate, Date validToDate, Byte status,
			Date lastUpdatedOn, Integer lastUpdatedBy) {
		this.userRegistrationInfoByFromUserId = userRegistrationInfoByFromUserId;
		this.userRegistrationInfoByToUserId = userRegistrationInfoByToUserId;
		this.notificationType = notificationType;
		this.subject = subject;
		this.description = description;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.validFromDate = validFromDate;
		this.validToDate = validToDate;
		this.status = status;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "from_user_id")
	public UserRegistrationInfo getUserRegistrationInfoByFromUserId() {
		return this.userRegistrationInfoByFromUserId;
	}

	public void setUserRegistrationInfoByFromUserId(
			UserRegistrationInfo userRegistrationInfoByFromUserId) {
		this.userRegistrationInfoByFromUserId = userRegistrationInfoByFromUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "to_user_id")
	public UserRegistrationInfo getUserRegistrationInfoByToUserId() {
		return this.userRegistrationInfoByToUserId;
	}

	public void setUserRegistrationInfoByToUserId(
			UserRegistrationInfo userRegistrationInfoByToUserId) {
		this.userRegistrationInfoByToUserId = userRegistrationInfoByToUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "notification_type_id")
	public NotificationType getNotificationType() {
		return this.notificationType;
	}

	public void setNotificationType(NotificationType notificationType) {
		this.notificationType = notificationType;
	}

	@Column(name = "subject", length = 200)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", length = 10)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_from_date", length = 10)
	public Date getValidFromDate() {
		return this.validFromDate;
	}

	public void setValidFromDate(Date validFromDate) {
		this.validFromDate = validFromDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_to_date", length = 10)
	public Date getValidToDate() {
		return this.validToDate;
	}

	public void setValidToDate(Date validToDate) {
		this.validToDate = validToDate;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
