package com.school.model;

// Generated Jun 9, 2015 5:02:23 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RoleLeaveTracking generated by hbm2java
 */
@Entity
@Table(name = "role_leave_tracking", catalog = "school_db")
public class RoleLeaveTracking implements java.io.Serializable {

	private Integer id;
	private Role role;
	private School school;
	private Date lastUpdatedOn;
	private Short leaveTypeId;
	private Float noOfDays;
	private Integer lastUpdatedBy;
	private Set userLeaveBalances = new HashSet(0);

	public RoleLeaveTracking() {
	}

	public RoleLeaveTracking(Role role, School school, Date lastUpdatedOn,
			Short leaveTypeId, Float noOfDays, Integer lastUpdatedBy,
			Set userLeaveBalances) {
		this.role = role;
		this.school = school;
		this.lastUpdatedOn = lastUpdatedOn;
		this.leaveTypeId = leaveTypeId;
		this.noOfDays = noOfDays;
		this.lastUpdatedBy = lastUpdatedBy;
		this.userLeaveBalances = userLeaveBalances;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id")
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "leave_type_id")
	public Short getLeaveTypeId() {
		return this.leaveTypeId;
	}

	public void setLeaveTypeId(Short leaveTypeId) {
		this.leaveTypeId = leaveTypeId;
	}

	@Column(name = "no_of_days", precision = 9, scale = 3)
	public Float getNoOfDays() {
		return this.noOfDays;
	}

	public void setNoOfDays(Float noOfDays) {
		this.noOfDays = noOfDays;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleLeaveTracking")
	public Set getUserLeaveBalances() {
		return this.userLeaveBalances;
	}

	public void setUserLeaveBalances(Set userLeaveBalances) {
		this.userLeaveBalances = userLeaveBalances;
	}

}
