package com.school.model;

// Generated Jun 26, 2015 2:39:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "school_db")
public class Role implements java.io.Serializable {

	private Short id;
	private String name;
	private Byte status;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;
	private Set<RoleLeaveTracking> roleLeaveTrackings = new HashSet<RoleLeaveTracking>(
			0);
	private Set<SecondaryRole> secondaryRoles = new HashSet<SecondaryRole>(0);

	public Role() {
	}

	public Role(String name, Byte status, Date lastUpdatedOn,
			Integer lastUpdatedBy, Set<RoleLeaveTracking> roleLeaveTrackings,
			Set<SecondaryRole> secondaryRoles) {
		this.name = name;
		this.status = status;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
		this.roleLeaveTrackings = roleLeaveTrackings;
		this.secondaryRoles = secondaryRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<RoleLeaveTracking> getRoleLeaveTrackings() {
		return this.roleLeaveTrackings;
	}

	public void setRoleLeaveTrackings(Set<RoleLeaveTracking> roleLeaveTrackings) {
		this.roleLeaveTrackings = roleLeaveTrackings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<SecondaryRole> getSecondaryRoles() {
		return this.secondaryRoles;
	}

	public void setSecondaryRoles(Set<SecondaryRole> secondaryRoles) {
		this.secondaryRoles = secondaryRoles;
	}

}
