package com.school.model;

// Generated Jun 26, 2015 2:39:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SafetyCategory generated by hbm2java
 */
@Entity
@Table(name = "safety_category")
public class SafetyCategory implements java.io.Serializable {

	private Integer id;
	private String name;
	private Byte status;
	private String description;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;
	private Set<SafetyCategoryItem> safetyCategoryItems = new HashSet<SafetyCategoryItem>(
			0);

	public SafetyCategory() {
	}

	public SafetyCategory(String name, Byte status, String description,
			Date lastUpdatedOn, Integer lastUpdatedBy,
			Set<SafetyCategoryItem> safetyCategoryItems) {
		this.name = name;
		this.status = status;
		this.description = description;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
		this.safetyCategoryItems = safetyCategoryItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "safetyCategory")
	public Set<SafetyCategoryItem> getSafetyCategoryItems() {
		return this.safetyCategoryItems;
	}

	public void setSafetyCategoryItems(
			Set<SafetyCategoryItem> safetyCategoryItems) {
		this.safetyCategoryItems = safetyCategoryItems;
	}

}
