package com.school.model;

// Generated Jun 26, 2015 2:39:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalesInfo generated by hbm2java
 */
@Entity
@Table(name = "sales_info")
public class SalesInfo implements java.io.Serializable {

	private Integer id;
	private School school;
	private Integer salesExecutiveId;
	private Integer dataCollectorId;
	private String infoProviderDesignation;
	private String infoProviderName;
	private String infoProviderContactNo;
	private String infoProviderEmail;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;

	public SalesInfo() {
	}

	public SalesInfo(School school, Integer salesExecutiveId,
			Integer dataCollectorId, String infoProviderDesignation,
			String infoProviderName, String infoProviderContactNo,
			String infoProviderEmail, Date lastUpdatedOn, Integer lastUpdatedBy) {
		this.school = school;
		this.salesExecutiveId = salesExecutiveId;
		this.dataCollectorId = dataCollectorId;
		this.infoProviderDesignation = infoProviderDesignation;
		this.infoProviderName = infoProviderName;
		this.infoProviderContactNo = infoProviderContactNo;
		this.infoProviderEmail = infoProviderEmail;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id")
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Column(name = "sales_executive_id")
	public Integer getSalesExecutiveId() {
		return this.salesExecutiveId;
	}

	public void setSalesExecutiveId(Integer salesExecutiveId) {
		this.salesExecutiveId = salesExecutiveId;
	}

	@Column(name = "data_collector_id")
	public Integer getDataCollectorId() {
		return this.dataCollectorId;
	}

	public void setDataCollectorId(Integer dataCollectorId) {
		this.dataCollectorId = dataCollectorId;
	}

	@Column(name = "info_provider_designation", length = 200)
	public String getInfoProviderDesignation() {
		return this.infoProviderDesignation;
	}

	public void setInfoProviderDesignation(String infoProviderDesignation) {
		this.infoProviderDesignation = infoProviderDesignation;
	}

	@Column(name = "info_provider_name", length = 200)
	public String getInfoProviderName() {
		return this.infoProviderName;
	}

	public void setInfoProviderName(String infoProviderName) {
		this.infoProviderName = infoProviderName;
	}

	@Column(name = "info_provider_contact_no", length = 20)
	public String getInfoProviderContactNo() {
		return this.infoProviderContactNo;
	}

	public void setInfoProviderContactNo(String infoProviderContactNo) {
		this.infoProviderContactNo = infoProviderContactNo;
	}

	@Column(name = "info_provider_email", length = 200)
	public String getInfoProviderEmail() {
		return this.infoProviderEmail;
	}

	public void setInfoProviderEmail(String infoProviderEmail) {
		this.infoProviderEmail = infoProviderEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
