package com.school.model;

// Generated Jun 26, 2015 2:39:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SchoolBoard generated by hbm2java
 */
@Entity
@Table(name = "school_board")
public class SchoolBoard implements java.io.Serializable {

	private Integer id;
	private BoardType boardType;
	private School school;

	public SchoolBoard() {
	}

	public SchoolBoard(BoardType boardType, School school) {
		this.boardType = boardType;
		this.school = school;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "board_type_id", nullable = false)
	public BoardType getBoardType() {
		return this.boardType;
	}

	public void setBoardType(BoardType boardType) {
		this.boardType = boardType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

}
