package com.school.model;

// Generated 2 Jun, 2015 2:50:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SchoolCategoryOptionFeature generated by hbm2java
 */
@Entity
@Table(name = "school_category_option_feature")
public class SchoolCategoryOptionFeature implements java.io.Serializable {

	private Integer id;
	private School school;
	private Integer categoryOptionId;
	private String value;
	private Float subWeightage;
	private Short sortOrder;

	public SchoolCategoryOptionFeature() {
	}

	public SchoolCategoryOptionFeature(School school, Integer categoryOptionId,
			String value, Float subWeightage, Short sortOrder) {
		this.school = school;
		this.categoryOptionId = categoryOptionId;
		this.value = value;
		this.subWeightage = subWeightage;
		this.sortOrder = sortOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id")
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Column(name = "category_option_id")
	public Integer getCategoryOptionId() {
		return this.categoryOptionId;
	}

	public void setCategoryOptionId(Integer categoryOptionId) {
		this.categoryOptionId = categoryOptionId;
	}

	@Column(name = "value", length = 500)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "sub_weightage", precision = 9, scale = 3)
	public Float getSubWeightage() {
		return this.subWeightage;
	}

	public void setSubWeightage(Float subWeightage) {
		this.subWeightage = subWeightage;
	}

	@Column(name = "sort_order")
	public Short getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Short sortOrder) {
		this.sortOrder = sortOrder;
	}

}
