package com.school.model;

//Generated Jun 29, 2015 2:37:56 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* SchoolSearchId generated by hbm2java
*/
@Entity
@Table(name = "school_search")
public class SchoolSearch implements java.io.Serializable {

	private int schoolId;
	private String name;
	private String alias;
	private String latitude;
	private String longitude;
	private String tagLine;
	private String aboutSchool;
	private String logo;
	private String homeImage;
	private Byte establishmentType;
	private String streetName;
	private String pincode;
	private String localityName;
	private String cityName;
	private String boardName;
	private String mediums;
	private String schoolCategory;
	private String schoolClassification;
	private Float rating;
	private long galeryImages;
	private long reviews;

	public SchoolSearch() {
	}

	public SchoolSearch(int schoolId, String boardName, long galeryImages,
			long reviews) {
		this.schoolId = schoolId;
		this.boardName = boardName;
		this.galeryImages = galeryImages;
		this.reviews = reviews;
	}

	public SchoolSearch(int schoolId, String name, String alias,
			String latitude, String longitude, String tagLine,
			String aboutSchool, String logo, String homeImage,
			Byte establishmentType, String streetName, String pincode,
			String localityName, String cityName, String boardName,
			String mediums, String schoolCategory, String schoolClassification,
			Float rating, long galeryImages, long reviews) {
		this.schoolId = schoolId;
		this.name = name;
		this.alias = alias;
		this.latitude = latitude;
		this.longitude = longitude;
		this.tagLine = tagLine;
		this.aboutSchool = aboutSchool;
		this.logo = logo;
		this.homeImage = homeImage;
		this.establishmentType = establishmentType;
		this.streetName = streetName;
		this.pincode = pincode;
		this.localityName = localityName;
		this.cityName = cityName;
		this.boardName = boardName;
		this.mediums = mediums;
		this.schoolCategory = schoolCategory;
		this.schoolClassification = schoolClassification;
		this.rating = rating;
		this.galeryImages = galeryImages;
		this.reviews = reviews;
	}
	
	@Id
	@Column(name = "school_id", unique = true, nullable = false)
	public int getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "alias", length = 200)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "latitude", length = 15)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", length = 15)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "tag_line", length = 200)
	public String getTagLine() {
		return this.tagLine;
	}

	public void setTagLine(String tagLine) {
		this.tagLine = tagLine;
	}

	@Column(name = "about_school", length = 65535)
	public String getAboutSchool() {
		return this.aboutSchool;
	}

	public void setAboutSchool(String aboutSchool) {
		this.aboutSchool = aboutSchool;
	}

	@Column(name = "logo", length = 200)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "home_image", length = 200)
	public String getHomeImage() {
		return this.homeImage;
	}

	public void setHomeImage(String homeImage) {
		this.homeImage = homeImage;
	}

	@Column(name = "establishment_type")
	public Byte getEstablishmentType() {
		return this.establishmentType;
	}

	public void setEstablishmentType(Byte establishmentType) {
		this.establishmentType = establishmentType;
	}

	@Column(name = "street_name", length = 500)
	public String getStreetName() {
		return this.streetName;
	}

	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}

	@Column(name = "pincode", length = 100)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "locality_name", length = 200)
	public String getLocalityName() {
		return this.localityName;
	}

	public void setLocalityName(String localityName) {
		this.localityName = localityName;
	}

	@Column(name = "city_name", length = 200)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "board_name", nullable = false, length = 45)
	public String getBoardName() {
		return this.boardName;
	}

	public void setBoardName(String boardName) {
		this.boardName = boardName;
	}

	@Column(name = "mediums", length = 65535)
	public String getMediums() {
		return this.mediums;
	}

	public void setMediums(String mediums) {
		this.mediums = mediums;
	}

	@Column(name = "school_category", length = 200)
	public String getSchoolCategory() {
		return this.schoolCategory;
	}

	public void setSchoolCategory(String schoolCategory) {
		this.schoolCategory = schoolCategory;
	}

	@Column(name = "school_classification", length = 200)
	public String getSchoolClassification() {
		return this.schoolClassification;
	}

	public void setSchoolClassification(String schoolClassification) {
		this.schoolClassification = schoolClassification;
	}

	@Column(name = "rating", precision = 9, scale = 3)
	public Float getRating() {
		return this.rating;
	}

	public void setRating(Float rating) {
		this.rating = rating;
	}

	@Column(name = "galery_images", nullable = false)
	public long getGaleryImages() {
		return this.galeryImages;
	}

	public void setGaleryImages(long galeryImages) {
		this.galeryImages = galeryImages;
	}

	@Column(name = "reviews", nullable = false)
	public long getReviews() {
		return this.reviews;
	}

	public void setReviews(long reviews) {
		this.reviews = reviews;
	}

}
