package com.school.model;

// Generated 2 Jun, 2015 2:50:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SchoolBoard generated by hbm2java
 */
@Entity
@Table(name = "school_board", catalog = "school_db")
public class SchoolBoard implements java.io.Serializable {

	private Integer id;
	private SchoolBoard schoolBoard;
	private short boardTypeId;
	private Set schoolBoards = new HashSet(0);

	public SchoolBoard() {
	}

	public SchoolBoard(SchoolBoard schoolBoard, short boardTypeId) {
		this.schoolBoard = schoolBoard;
		this.boardTypeId = boardTypeId;
	}

	public SchoolBoard(SchoolBoard schoolBoard, short boardTypeId,
			Set schoolBoards) {
		this.schoolBoard = schoolBoard;
		this.boardTypeId = boardTypeId;
		this.schoolBoards = schoolBoards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public SchoolBoard getSchoolBoard() {
		return this.schoolBoard;
	}

	public void setSchoolBoard(SchoolBoard schoolBoard) {
		this.schoolBoard = schoolBoard;
	}

	@Column(name = "board_type_id", nullable = false)
	public short getBoardTypeId() {
		return this.boardTypeId;
	}

	public void setBoardTypeId(short boardTypeId) {
		this.boardTypeId = boardTypeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schoolBoard")
	public Set getSchoolBoards() {
		return this.schoolBoards;
	}

	public void setSchoolBoards(Set schoolBoards) {
		this.schoolBoards = schoolBoards;
	}

}
