package com.school.model;

// Generated 2 Jun, 2015 2:50:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SchoolInfo generated by hbm2java
 */
@Entity
@Table(name = "school_info", catalog = "school_db")
public class SchoolInfo implements java.io.Serializable {

	private Integer id;
	private SchoolType schoolType;
	private SchoolCategoryType schoolCategoryType;
	private SchoolClassificationType schoolClassificationType;
	private School school;
	private String schoolWebsite;
	private String awardDesc;
	private String tieUpDesc;
	private String approvalDesc;
	private Date lastUpdatedOn;
	private Date lastUpdatedBy;

	public SchoolInfo() {
	}

	public SchoolInfo(SchoolType schoolType,
			SchoolCategoryType schoolCategoryType,
			SchoolClassificationType schoolClassificationType, School school,
			String schoolWebsite, String awardDesc, String tieUpDesc,
			String approvalDesc, Date lastUpdatedOn, Date lastUpdatedBy) {
		this.schoolType = schoolType;
		this.schoolCategoryType = schoolCategoryType;
		this.schoolClassificationType = schoolClassificationType;
		this.school = school;
		this.schoolWebsite = schoolWebsite;
		this.awardDesc = awardDesc;
		this.tieUpDesc = tieUpDesc;
		this.approvalDesc = approvalDesc;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_type_id")
	public SchoolType getSchoolType() {
		return this.schoolType;
	}

	public void setSchoolType(SchoolType schoolType) {
		this.schoolType = schoolType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_category_type_id")
	public SchoolCategoryType getSchoolCategoryType() {
		return this.schoolCategoryType;
	}

	public void setSchoolCategoryType(SchoolCategoryType schoolCategoryType) {
		this.schoolCategoryType = schoolCategoryType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "classification_type_id")
	public SchoolClassificationType getSchoolClassificationType() {
		return this.schoolClassificationType;
	}

	public void setSchoolClassificationType(
			SchoolClassificationType schoolClassificationType) {
		this.schoolClassificationType = schoolClassificationType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id")
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Column(name = "school_website", length = 200)
	public String getSchoolWebsite() {
		return this.schoolWebsite;
	}

	public void setSchoolWebsite(String schoolWebsite) {
		this.schoolWebsite = schoolWebsite;
	}

	@Column(name = "award_desc", length = 65535)
	public String getAwardDesc() {
		return this.awardDesc;
	}

	public void setAwardDesc(String awardDesc) {
		this.awardDesc = awardDesc;
	}

	@Column(name = "tie_up_desc", length = 65535)
	public String getTieUpDesc() {
		return this.tieUpDesc;
	}

	public void setTieUpDesc(String tieUpDesc) {
		this.tieUpDesc = tieUpDesc;
	}

	@Column(name = "approval_desc", length = 65535)
	public String getApprovalDesc() {
		return this.approvalDesc;
	}

	public void setApprovalDesc(String approvalDesc) {
		this.approvalDesc = approvalDesc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated_on", length = 10)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated_by", length = 10)
	public Date getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Date lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
