package com.school.model;

// Generated Jun 26, 2015 2:39:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SchoolSafetyCatItem generated by hbm2java
 */
@Entity
@Table(name = "school_safety_cat_item", catalog = "school_db")
public class SchoolSafetyCatItem implements java.io.Serializable {

	private Integer id;
	private SafetyCategoryItem safetyCategoryItem;
	private School school;
	private Byte isDeleted;
	private String fieldLabel;
	private String fieldValue;

	public SchoolSafetyCatItem() {
	}

	public SchoolSafetyCatItem(SafetyCategoryItem safetyCategoryItem,
			School school, Byte isDeleted, String fieldLabel, String fieldValue) {
		this.safetyCategoryItem = safetyCategoryItem;
		this.school = school;
		this.isDeleted = isDeleted;
		this.fieldLabel = fieldLabel;
		this.fieldValue = fieldValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "safety_category_item_id")
	public SafetyCategoryItem getSafetyCategoryItem() {
		return this.safetyCategoryItem;
	}

	public void setSafetyCategoryItem(SafetyCategoryItem safetyCategoryItem) {
		this.safetyCategoryItem = safetyCategoryItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id")
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Column(name = "is_deleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "field_label", length = 50)
	public String getFieldLabel() {
		return this.fieldLabel;
	}

	public void setFieldLabel(String fieldLabel) {
		this.fieldLabel = fieldLabel;
	}

	@Column(name = "field_value", length = 100)
	public String getFieldValue() {
		return this.fieldValue;
	}

	public void setFieldValue(String fieldValue) {
		this.fieldValue = fieldValue;
	}

}
