package com.school.model;

// Generated Jun 16, 2015 4:57:47 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentSchoolInfo generated by hbm2java
 */
@Entity
@Table(name = "student_school_info", catalog = "school_db")
public class StudentSchoolInfo implements java.io.Serializable {

	private Integer id;
	private School school;
	private StudentPersonalInfo studentPersonalInfo;
	private String enrollNo;
	private String rollNo;
	private Boolean schoolBusOption;
	private Date admissionDate;
	private Date session;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;
	private String motherContactNo;

	public StudentSchoolInfo() {
	}

	public StudentSchoolInfo(School school,
			StudentPersonalInfo studentPersonalInfo, String enrollNo,
			String rollNo, Boolean schoolBusOption, Date admissionDate,
			Date session, Date lastUpdatedOn, Integer lastUpdatedBy,
			String motherContactNo) {
		this.school = school;
		this.studentPersonalInfo = studentPersonalInfo;
		this.enrollNo = enrollNo;
		this.rollNo = rollNo;
		this.schoolBusOption = schoolBusOption;
		this.admissionDate = admissionDate;
		this.session = session;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
		this.motherContactNo = motherContactNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id")
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public StudentPersonalInfo getStudentPersonalInfo() {
		return this.studentPersonalInfo;
	}

	public void setStudentPersonalInfo(StudentPersonalInfo studentPersonalInfo) {
		this.studentPersonalInfo = studentPersonalInfo;
	}

	@Column(name = "enroll_no", length = 20)
	public String getEnrollNo() {
		return this.enrollNo;
	}

	public void setEnrollNo(String enrollNo) {
		this.enrollNo = enrollNo;
	}

	@Column(name = "roll_no", length = 40)
	public String getRollNo() {
		return this.rollNo;
	}

	public void setRollNo(String rollNo) {
		this.rollNo = rollNo;
	}

	@Column(name = "school_bus_option")
	public Boolean getSchoolBusOption() {
		return this.schoolBusOption;
	}

	public void setSchoolBusOption(Boolean schoolBusOption) {
		this.schoolBusOption = schoolBusOption;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "admission_date", length = 10)
	public Date getAdmissionDate() {
		return this.admissionDate;
	}

	public void setAdmissionDate(Date admissionDate) {
		this.admissionDate = admissionDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "session", length = 10)
	public Date getSession() {
		return this.session;
	}

	public void setSession(Date session) {
		this.session = session;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Column(name = "mother_contact_no", length = 15)
	public String getMotherContactNo() {
		return this.motherContactNo;
	}

	public void setMotherContactNo(String motherContactNo) {
		this.motherContactNo = motherContactNo;
	}

}
