package com.school.model;

// Generated 2 Jun, 2015 2:50:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudentSchoolFeeInfo generated by hbm2java
 */
@Entity
@Table(name = "student_school_fee_info", catalog = "school_db")
public class StudentSchoolFeeInfo implements java.io.Serializable {

	private StudentSchoolFeeInfoId id;
	private SchoolFeeDetail schoolFeeDetail;
	private StudentPersonalInfo studentPersonalInfo;

	public StudentSchoolFeeInfo() {
	}

	public StudentSchoolFeeInfo(StudentSchoolFeeInfoId id) {
		this.id = id;
	}

	public StudentSchoolFeeInfo(StudentSchoolFeeInfoId id,
			SchoolFeeDetail schoolFeeDetail,
			StudentPersonalInfo studentPersonalInfo) {
		this.id = id;
		this.schoolFeeDetail = schoolFeeDetail;
		this.studentPersonalInfo = studentPersonalInfo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "schoolFeeDetailId", column = @Column(name = "school_fee_detail_id")),
			@AttributeOverride(name = "studentId", column = @Column(name = "student_id")),
			@AttributeOverride(name = "paidOn", column = @Column(name = "paid_on", length = 10)),
			@AttributeOverride(name = "isPaymentComplete", column = @Column(name = "is_payment_complete")),
			@AttributeOverride(name = "amountPaid", column = @Column(name = "amount_paid", precision = 9, scale = 3)),
			@AttributeOverride(name = "parentId", column = @Column(name = "parent_id")),
			@AttributeOverride(name = "description", column = @Column(name = "description")),
			@AttributeOverride(name = "isDeleted", column = @Column(name = "is_deleted")),
			@AttributeOverride(name = "lastUpdatedOn", column = @Column(name = "last_updated_on", length = 10)),
			@AttributeOverride(name = "lastUpdatedBy", column = @Column(name = "last_updated_by")) })
	public StudentSchoolFeeInfoId getId() {
		return this.id;
	}

	public void setId(StudentSchoolFeeInfoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_fee_detail_id", insertable = false, updatable = false)
	public SchoolFeeDetail getSchoolFeeDetail() {
		return this.schoolFeeDetail;
	}

	public void setSchoolFeeDetail(SchoolFeeDetail schoolFeeDetail) {
		this.schoolFeeDetail = schoolFeeDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", insertable = false, updatable = false)
	public StudentPersonalInfo getStudentPersonalInfo() {
		return this.studentPersonalInfo;
	}

	public void setStudentPersonalInfo(StudentPersonalInfo studentPersonalInfo) {
		this.studentPersonalInfo = studentPersonalInfo;
	}

}
