package com.school.model;

// Generated Jun 9, 2015 5:02:23 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentClass generated by hbm2java
 */
@Entity
@Table(name = "student_class", catalog = "school_db")
public class StudentClass implements java.io.Serializable {

	private Integer id;
	private ClassInfo classInfo;
	private StudentPersonalInfo studentPersonalInfo;
	private ClassSection classSection;
	private String passOutYear;
	private Boolean isCurrent;
	private Date startTermDate;
	private Date termEndDate;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;

	public StudentClass() {
	}

	public StudentClass(ClassInfo classInfo,
			StudentPersonalInfo studentPersonalInfo, ClassSection classSection,
			String passOutYear, Boolean isCurrent, Date startTermDate,
			Date termEndDate, Date lastUpdatedOn, Integer lastUpdatedBy) {
		this.classInfo = classInfo;
		this.studentPersonalInfo = studentPersonalInfo;
		this.classSection = classSection;
		this.passOutYear = passOutYear;
		this.isCurrent = isCurrent;
		this.startTermDate = startTermDate;
		this.termEndDate = termEndDate;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id")
	public ClassInfo getClassInfo() {
		return this.classInfo;
	}

	public void setClassInfo(ClassInfo classInfo) {
		this.classInfo = classInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public StudentPersonalInfo getStudentPersonalInfo() {
		return this.studentPersonalInfo;
	}

	public void setStudentPersonalInfo(StudentPersonalInfo studentPersonalInfo) {
		this.studentPersonalInfo = studentPersonalInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "section_id")
	public ClassSection getClassSection() {
		return this.classSection;
	}

	public void setClassSection(ClassSection classSection) {
		this.classSection = classSection;
	}

	@Column(name = "pass_out_year", length = 4)
	public String getPassOutYear() {
		return this.passOutYear;
	}

	public void setPassOutYear(String passOutYear) {
		this.passOutYear = passOutYear;
	}

	@Column(name = "is_current")
	public Boolean getIsCurrent() {
		return this.isCurrent;
	}

	public void setIsCurrent(Boolean isCurrent) {
		this.isCurrent = isCurrent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_term_date", length = 10)
	public Date getStartTermDate() {
		return this.startTermDate;
	}

	public void setStartTermDate(Date startTermDate) {
		this.startTermDate = startTermDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "term_end_date", length = 10)
	public Date getTermEndDate() {
		return this.termEndDate;
	}

	public void setTermEndDate(Date termEndDate) {
		this.termEndDate = termEndDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
