package com.school.model;

// Generated Jun 26, 2015 2:39:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TeacherHomeworkRemarks generated by hbm2java
 */
@Entity
@Table(name = "teacher_homework_remarks")
public class TeacherHomeworkRemarks implements java.io.Serializable {

	private Integer id;
	private TeacherHomework teacherHomework;
	private StudentPersonalInfo studentPersonalInfo;
	private String remarksDesc;
	private Byte isDeleted;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;

	public TeacherHomeworkRemarks() {
	}

	public TeacherHomeworkRemarks(TeacherHomework teacherHomework,
			StudentPersonalInfo studentPersonalInfo, String remarksDesc,
			Byte isDeleted, Date lastUpdatedOn, Integer lastUpdatedBy) {
		this.teacherHomework = teacherHomework;
		this.studentPersonalInfo = studentPersonalInfo;
		this.remarksDesc = remarksDesc;
		this.isDeleted = isDeleted;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homework_id")
	public TeacherHomework getTeacherHomework() {
		return this.teacherHomework;
	}

	public void setTeacherHomework(TeacherHomework teacherHomework) {
		this.teacherHomework = teacherHomework;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public StudentPersonalInfo getStudentPersonalInfo() {
		return this.studentPersonalInfo;
	}

	public void setStudentPersonalInfo(StudentPersonalInfo studentPersonalInfo) {
		this.studentPersonalInfo = studentPersonalInfo;
	}

	@Column(name = "remarks_desc")
	public String getRemarksDesc() {
		return this.remarksDesc;
	}

	public void setRemarksDesc(String remarksDesc) {
		this.remarksDesc = remarksDesc;
	}

	@Column(name = "is_deleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
